# Neural Network

For this project, I will build 2 neural networks in order to model over a seed dataset and an iris dataset.

## How can neural networks be used?

### Seed Dataset
The neural netowrk trained by the seed dataset will be used to predict which seeds belong to which 3 different wheat categories: Kama, Rosa or Canadian. It will provide a prediction given a set of features such as area A, perimeter P, compactness C = 4piA/P^2, length of kernel, width of kernel, its' asymmetry coefficient, and the length of kernel groove.

### Iris Dataset
The neural netowrk trained by the iris dataset will be used to predict the 3 different iris categories: setosa, versicolor, and virginica. It will provide a prediction given a set of features such as the petal length, petal width, sepal length, and sepal width.

In [1]:
import pandas as pd
import numpy as np
from math import exp
from random import random

In [2]:
seed_df = pd.read_csv("../data/seed.csv") 
iris_df = pd.read_csv("../data/iris.csv")

## Data Preview

In [3]:
seed_df

         A      P       C     LK     WK  A_Coef    LKG  target
0    15.26  14.84  0.8710  5.763  3.312   2.221  5.220       0
1    14.88  14.57  0.8811  5.554  3.333   1.018  4.956       0
2    14.29  14.09  0.9050  5.291  3.337   2.699  4.825       0
3    13.84  13.94  0.8955  5.324  3.379   2.259  4.805       0
4    16.14  14.99  0.9034  5.658  3.562   1.355  5.175       0
..     ...    ...     ...    ...    ...     ...    ...     ...
205  12.19  13.20  0.8783  5.137  2.981   3.631  4.870       2
206  11.23  12.88  0.8511  5.140  2.795   4.325  5.003       2
207  13.20  13.66  0.8883  5.236  3.232   8.315  5.056       2
208  11.84  13.21  0.8521  5.175  2.836   3.598  5.044       2
209  12.30  13.34  0.8684  5.243  2.974   5.637  5.063       2

[210 rows x 8 columns]

In [4]:
iris_df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

## Data Pre-processing

### For the seed dataset

In [5]:
# Split data set for training and testing
msk = np.random.rand(len(seed_df)) < 0.8
seed_train = seed_df[msk]
seed_train_data = seed_train.values[:,0:8]
seed_test = seed_df[~msk]
seed_test_data = seed_test.values[:,0:8]

# Rescale and normalize features to be betweeon 0 to 1
min_max_seed_train = [[min(column), max(column)] for column in zip(*seed_train_data)]
for row in seed_train_data:
    for i in range(len(row) - 1):
        row[i] = (row[i] - min_max_seed_train[i][0]) / (min_max_seed_train[i][1] - min_max_seed_train[i][0])
min_max_seed_test = [[min(column), max(column)] for column in zip(*seed_test_data)]
for row in seed_test_data:
    for i in range(len(row) - 1):
        row[i] = (row[i] - min_max_seed_test[i][0]) / (min_max_seed_test[i][1] - min_max_seed_test[i][0])

### For the iris dataset

In [6]:
del iris_df['Id']

# Transform category text data into numbers
labelEncoding = {'Species': {"Iris-setosa": 0, "Iris-versicolor": 1, "Iris-virginica": 2}}
iris_df = iris_df.replace(labelEncoding)

msk = np.random.rand(len(iris_df)) < 0.8
iris_train = iris_df[msk]
iris_train_data = iris_train.values[:,0:5]
iris_test = iris_df[~msk]
iris_test_data = iris_test.values[:,0:5]

min_max_iris_train = [[min(column), max(column)] for column in zip(*iris_train_data)]
for row in iris_train_data:
    for i in range(len(row) - 1):
        row[i] = (row[i] - min_max_iris_train[i][0]) / (min_max_iris_train[i][1] - min_max_iris_train[i][0])
min_max_iris_test = [[min(column), max(column)] for column in zip(*iris_test_data)]
for row in iris_test_data:
    for i in range(len(row) - 1):
        row[i] = (row[i] - min_max_iris_test[i][0]) / (min_max_iris_test[i][1] - min_max_iris_test[i][0])

## Building the Neural Network

In [7]:
def init_neural_network(num_inputs, num_outputs, num_hidden):
    neural_network = []
    hidden_layer = [{'weights':[random() for i in range(num_inputs + 1)]} for i in range(num_hidden)]
    output_layer = [{'weights':[random() for i in range(num_hidden + 1)]} for i in range(num_outputs)]
    # Randomly initialize the weights
    neural_network.append(hidden_layer)
    neural_network.append(output_layer)
    return neural_network

def train_neural_network(neural_network, training_set, learning_rate, num_epoch, num_outputs):
    for epoch in range(num_epoch):
        cost_error = 0
        for row in training_set:
            # Forward propagation to get hypothesis given feature
            hypothesis = row
            for layer in neural_network:
                inputs = []
                for unit in layer:
                    activation = unit['weights'][-1]
                    for i in range(len(unit['weights'])-1):
                        print(i)
                        activation += unit['weights'][i] * hypothesis[i]
                    unit['hypothesis'] = 1.0 / (1.0 + exp(-activation))
                    inputs.append(unit['hypothesis'])
                hypothesis = inputs
                
            # Cost error
            true_y = [0 for i in range(num_outputs)] 
            true_y[int(row[-1])] = 1
            cost_error += sum([(true_y[i]-hypothesis[i])**2 for i in range(len(true_y))])
            
            # Backward propagation
            for i in reversed(range(len(neural_network))):
                layer = neural_network[i]
                errors = []
                if i != len(neural_network) - 1:
                    for j in range(len(layer)):
                        error = 0.0
                        for unit in neural_network[i + 1]:
                            error += (unit['weights'][j] * unit['delta'])
                        errors.append(error)
                else:
                    for j in range(len(layer)):
                        unit = layer[j]
                        errors.append(true_y[j] - unit['hypothesis'])
                for j in range(len(layer)):
                    unit = layer[j]
                    unit['delta'] = errors[j] * unit['hypothesis'] * (1.0 - unit['hypothesis'])
                    
            # Gradient descent to update weight that minimize error
            for i in range(len(neural_network)):
                feature = row[:-1]
                if i != 0:
                    feature = [unit['hypothesis'] for unit in neural_network[i - 1]]
                for unit in neural_network[i]:
                    for j in range(len(feature)):
                        unit['weights'][j] += learning_rate * unit['delta'] * feature[j]
                    unit['weights'][-1] += learning_rate * unit['delta']
    print('Neural Network Sum Squared Error = ' + str(cost_error))

### Training the Neural Network using the Seed Data set

In [8]:
num_inputs = 7
num_outputs = 3
num_hidden = 3
seed_neural_network = init_neural_network(num_inputs, num_outputs, num_hidden) 
train_neural_network(seed_neural_network, seed_train_data, 0.2, 1000, num_outputs)

Neural Network Sum Squared Error = 5.074546978121341

As we can see above, our sum squared error is reduced to a low number. Therefore, the seed neural network should now be ready to be tested on the seed testing set.

### Training the Neural Networks using the Iris Data set

In [9]:
num_inputs = 4
num_outputs = 3
num_hidden = 3
iris_neural_network = init_neural_network(num_inputs, num_outputs, num_hidden) 
train_neural_network(seed_neural_network, iris_train_data, 0.2, 1000, num_outputs)

IndexError: index 5 is out of bounds for axis 0 with size 5

In [ ]:
for row in seed_test_data:
    hypothesis = row
    for layer in seed_neural_network:
        inputs = []
        for unit in layer:
            activation = unit['weights'][-1]
            for i in range(len(unit['weights'])-1):
                activation += unit['weights'][i] * hypothesis[i]
            unit['hypothesis'] = 1.0 / (1.0 + exp(-activation))
            inputs.append(unit['hypothesis'])
        hypothesis = inputs
    print('True value=' + str(int(row[-1])) + ', Hypothesis=' + str(hypothesis.index(max(hypothesis))))

In [13]:
iris_train_data[0][5]

IndexError: index 5 is out of bounds for axis 0 with size 5